# Generated by Django 5.1 on 2024-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_name_signup_username_alter_signup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('WB', 'West Bengal')], max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('disease', models.CharField(max_length=20)),
            ],
        ),
    ]
