# Generated by Django 5.1 on 2024-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
