# Generated by Django 5.1 on 2024-09-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_donor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='upload',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/'),
        ),
    ]
