# Generated by Django 5.1 on 2024-10-22 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_image_product_blood_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
