# Generated by Django 5.1 on 2024-10-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
