# Generated by Django 5.1 on 2024-10-27 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_donor_blood_group_donor_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
