# Generated by Django 5.1.2 on 2024-11-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_donor_blood_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='address',
            new_name='donor_address',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='city',
            new_name='donor_city',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='contact',
            new_name='donor_contact',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='disease',
            new_name='donor_disease',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='name',
            new_name='donor_name',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='state',
            new_name='donor_state',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='zip',
            new_name='donor_zip_code',
        ),
    ]
